### ISSUE TITLE
Cosmetica softlocks the game whenever its server fails to authenticate

### ISSUE THREAD

**Issue by VL4DST3R** [Cosmetica-cc/Cosmetica#133]
**Describe the bug**
Lately I've been getting popups from the mod as if its the first time I've installed it, locking me to follow its stupid tutorial about how to customize the character mid-gameplay, with no way to EXIT.

**To Reproduce**
1. I assume disconnect from the internet or somehow cause a failure to auth with the mod server.
2. Enjoy being stuck in the menus until it times out or manages to connect and authenticate.
3. (Optional) fall into lava or get wrecked in pvp as a result.
4. Joy.

**Expected behavior**
Never steal focus or lock the user inside its menus with no way to exit except alt-f4

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10
 - Minecraft Version 1.20.1 on latest fabric

**Additional context**
n/a

**Comment by Kissunen** [comment]
I can second this. The exact same thing happened me too, I think it was yesterday or the day before. Logged into a server I play on and Cosmetica came up with its full-screen welcome message / tutorial, with no way (or at least no obvious way) to exit from it immediately. Even the ESC key had no effect for going back.

Such a "pop-up" is super annoying, when you just want to play, and what makes it worse is that you can't seem to get out of it. It is a game-breaking issue and thus it should be fixed with a high priority.

Please let users configure their installation whenever they wish, instead of throwing it on their face as a full-screen popup view when logging in the game, especially since it happens also when it just can't seem to connect, even though you've already configured it earlier.

Thank you for looking into this.

**Comment by eyezahhhh** [comment]
This happens halfway through the game when the server is overloaded and can't reach the database to check if you're a new player. You can force disable the tutorial though, instructions [here](https://cosmetica.cc/docs/mod-configs)

**Comment by VL4DST3R** [comment]
This can happen multiple times during a play session (without exiting the server) even sometimes in close succession.

Consider adding the instructions here on github as well (a wiki tab) as I and undoubtedly many others had no idea that site even existed.

**Comment by eyezahhhh** [comment]
It's linked on the Curseforge and Modrinth pages. Not gonna add it here since it'll be outdated in v2

**Comment by VL4DST3R** [comment]
Has this been actually fixed? While disabling the tutorial works as a as a last resort, I figured you'd want to properly fix the underlying issue.

**Comment by eyezahhhh** [comment]
See above messages for cause of issue. Not much I can do about it right now so you'll need to deal with it or disable the tutorial until it's resolved
