### ISSUE TITLE
Incorrect handling of Wynntils

### ISSUE THREAD

**Issue by FayneAldan** [Cosmetica-cc/Cosmetica#73]
**Describe the bug**
Wynntils' API isn't properly checked, resulting in problems when disabling cosmetics.

**To Reproduce**
1. Login to the [Wynntils website](https://account.wynntils.com/)
  - If you don't have an account, type `/token` from the Wynntils mod to create an account.
2. Disable your cosmetics and save.
3. Check your Wynntils cape from Cosmetica.

**Expected behavior**
The Wynntils cape should be ignored and a different cape provider should be checked in its place.

**Screenshots**
- [Wynntils Profile](https://i.imgur.com/UtcylaK.png)
- [Placeholder Wynntils Cape on Cosmetica Profile](https://i.imgur.com/pq6QfRZ.png)
- [Placeholder Wynntils Elytra on Cosmetica Profile](https://i.imgur.com/FQB52um.png)
- [Placeholder Texture Returned by API](https://athena.wynntils.com/capes/user/4a17f918-4870-4ca5-8106-05869bb7e6e9)

**Setup (please complete the following information):**
 - OS: Windows 11
 - Minecraft Version: N/a
 - Version: N/a

**Additional context**
The user's options are returned by:
`https://athena.wynntils.com/user/getInfo/(UUID with dashes)`
Example: https://athena.wynntils.com/user/getInfo/4a17f918-4870-4ca5-8106-05869bb7e6e9
Example with a non-Wynntils user (Notch): https://athena.wynntils.com/user/getInfo/069a79f4-44e9-4726-a5be-fca90e38aaf5

**Comment by eyezahhhh** [comment]
Cosmetica pulls from https://athena.wynntils.com/capes/user/4a17f918-4870-4ca5-8106-05869bb7e6e9
instead of https://athena.wynntils.com/user/getInfo/4a17f918-4870-4ca5-8106-05869bb7e6e9

Both endpoints seem to return the same cape, however /capes/user seems to be missing the context of whether the cape should be equipped or not (I assume that's how the Wynntils API works). So I'll work on getting that context working.

Just so you know, Cosmetica caches third party capes for 12 hours, so changes may not be instant.

**Comment by eyezahhhh** [comment]
This has been fixed on Wynntils end, so we don't have to do anything. Our API may take up to 24 hours to flush all outdated capes.
